### ISSUE TITLE
Parse_uspto_xml package not found

### ISSUE THREAD

**Issue by Tharissi** [lettergram/parse-uspto-xml#29]
When I try to install the package parse_uspto_xml.utils I get an error: 

ModuleNotFoundError: No module named 'parse_uspto_xml.utils'
Although I have well-defined the directory. 

Are you using a specific Python application or a specific version? I am using it on Python 3.9.13.

**Comment by JGSweets** [comment]
Can you try:
1. Uninstalling the current version you have.
2.  Install it directly via git like the following:
```console
pip install git+https://github.com/lettergram/parse-uspto-xml.git
```

To me, it sounds like you have a working directory issue where it isn't properly referencing the path of the library. That's my best guess.
